### ISSUE TITLE
Backing up whole organisations does not work

### ISSUE THREAD

**Issue by KygekDev** [clockfort/GitHub-Backup#49]
I get the following error when trying to run `github-backup KygekDev . -o KygekTeam`, which I done based on https://github.com/clockfort/GitHub-Backup#how-to-back-up-entire-github-organisation-repos:

```
Traceback (most recent call last):
  File "/home/acer/.local/bin/github-backup", line 8, in <module>
    sys.exit(main())
  File "/home/acer/.local/lib/python3.8/site-packages/github_backup/github_backup.py", line 108, in main
    account = gh.get_organization(args.login_or_token)
  File "/home/acer/.local/lib/python3.8/site-packages/github/MainClass.py", line 296, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", f"/orgs/{login}")
  File "/home/acer/.local/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/acer/.local/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/orgs#get-an-organization"}
```

What can I do to fix/solve the issue?

**Comment by eclRDuran** [comment]
Same issue

**Comment by allem40306** [comment]
use github-backup <org_name> <dir_name> -o <org_name> to solve
(I use ssh-key to login github)
